AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "http_health_check.gemspec"

Style/CommentedKeyword:
  Enabled: false
