version: '3.5'
services:
  redis:
    image: bitnami/redis:6.2
    environment:
      REDIS_PASSWORD: supersecret
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

volumes:
  redis: {}
