name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]
    services:
      redis:
        image: bitnami/redis:6.2
        ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: supersecret
        options: >-
          --health-cmd "redis-cli -p 6379 -a 'supersecret' ping"
          --health-interval 1s
          --health-timeout 3s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run all tests
        run: bundle exec rspec
        env:
          REDIS_URL: redis://:supersecret@redis:${{ job.services.redis.ports[6379] }}/0
          # FIXME!
          SKIP_REDIS_SPECS: true
      - name: Run rubocop
        run: bundle exec rubocop
